driver:
  name: ec2
  aws_ssh_key_id: lab
  region: us-east-1
  availability_zone: c
  subnet_id: subnet-b630b09a
  instance_type: t2.micro
  image_id: ami-46c1b650
  security_group_ids: ["chef-281117-SG"]
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: 

platforms:
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[learn_chef_httpd::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
